import subprocess
import random
import os
import time
from logger import logger

new_prompt = """
    An error occurred: {error}. Please try again.
    And out is {out}, we dont see the flag. You may rethink your payload, like the offset of the stack. Maybe it is too big or too small.
    And just return the code, do not add any additional information.
    Dont quote the code block.
"""

def generate_random_filename():
    return f"exp_{int(time.time())}.py"

def write_exp(exp, filename):
    with open(filename, "w") as f:
        f.write(exp)

def expolit(url, payload_type, payload, payload_data):
    assert payload_type == "exp"
    exp_file_name = generate_random_filename()
    write_exp(payload, exp_file_name)
    p = subprocess.run(["python3", exp_file_name], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = p.stdout, p.stderr
    logger.info(f"{output = }")
    logger.info(f"{err = }")
    return output, new_prompt.format(error=err, out=output)