import subprocess
import random
import os
import time
from logger import logger
from async_helper import async_popen

new_prompt = """
    An error occurred: {error}. Please try again.
    And out is {out}, we dont see the flag. You may rethink your payload, like the offset of the stack. Maybe it is too big or too small.
    And just return the code, do not add any additional information.
    Dont quote the code block.
"""

def generate_random_filename():
    return f"exp_{int(time.time() * 1000000)}.py"

def write_exp(exp, filename):
    with open(filename, "w") as f:
        f.write(exp)

async def expolit(url, payload_type, payload, payload_data):
    assert payload_type == "exp"
    exp_file_name = generate_random_filename()
    write_exp(payload, exp_file_name)
    
    cmd = f"python3 {exp_file_name}"
    logger.info(f"Executing: {cmd}")
    output, err = await async_popen(cmd, 8)    # kill after 8s

    logger.info(f"{output = }")
    logger.info(f"{err = }")
    return output, new_prompt.format(error=err, out=output)
